// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwceydrkisetqkqjapta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3Y2V5ZHJraXNldHFrcWphcHRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MDUyNTAsImV4cCI6MjA1OTI4MTI1MH0.5QyhCQTilK8Ydg3_hwSNPpQH6C0cXK6f8tz9GkHdkEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);