// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugsyzrohxtokfdpqqqjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnc3l6cm9oeHRva2ZkcHFxcWpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxOTQ0MDYsImV4cCI6MjA1Nzc3MDQwNn0.9QWBWrG5OKLCErBTZTjuaptRFgC9kqVT3eWpzErOzVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);